name: droiddesk
description: "DroidDesk - Full Linux Desktop on Android"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  percent_indicator: ^4.2.3
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo.png
    - assets/bootstrap-aarch64.zip
    - assets/socket_hook.c

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
